# Generated by Django 4.1 on 2025-04-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0004_alter_movie_actors_alter_movie_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinemahall",
            name="rows",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="cinemahall",
            name="seats_in_row",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                related_name="movie_actors", to="cinema.actor"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                related_name="movie_genres", to="cinema.genre"
            ),
        ),
    ]
